/**
 * Rasterise the brand SVGs into the PNGs that platforms cannot render as SVG:
 *
 *   public/og-image.svg -> public/og-image.png      (1200x630 social card)
 *   public/favicon.svg  -> public/apple-touch-icon.png, icon-192.png, icon-512.png
 *
 * Social platforms (Facebook, LinkedIn, X, WhatsApp) and iOS home screens do
 * not accept SVG, so these PNGs are what the meta tags and web manifest point
 * at. Run `npm run og` after editing either SVG, then commit the output.
 *
 * `sharp` is a devDependency only — it never ships in the browser bundle.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const at = (name) => fileURLToPath(new URL(`../public/${name}`, import.meta.url))

async function write(name, buffer) {
  await writeFile(at(name), buffer)
  console.log(`${name.padEnd(22)} ${(buffer.length / 1024).toFixed(0)} KB`)
}

// --- Brand geometry ----------------------------------------------------------
// The glyph lives in one place. The two static SVGs in public/ cannot import
// TypeScript, so they are generated from it here rather than hand-copied —
// three hand-maintained copies of a 4KB path would drift immediately.
const brandSource = await readFile(
  fileURLToPath(new URL('../src/components/brand/pandaPath.ts', import.meta.url)),
  'utf8',
)
const pandaPath = brandSource.match(/export const PANDA_PATH\s*=\s*\n?\s*'([^']+)'/)?.[1]
if (!pandaPath) throw new Error('Could not read PANDA_PATH from pandaPath.ts')

// favicon.svg — the plate stays light in both colour schemes: a panda is dark
// markings on a light face, so inverting produces a negative that reads as
// some other animal.
await writeFile(
  at('favicon.svg'),
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <title>Panda Smart Home</title>
  <!-- Generated by \`npm run og\` from src/components/brand/pandaPath.ts. Do not edit. -->
  <rect width="512" height="512" rx="115" fill="#fbfbf9"/>
  <g transform="translate(256 256) scale(0.95) translate(-237 -235)">
    <path d="${pandaPath}" fill="#0c0f13" fill-rule="evenodd"/>
  </g>
</svg>
`,
)
console.log('favicon.svg           regenerated from pandaPath.ts')

// og-image.svg keeps its hand-authored layout; only the glyph is injected.
const ogSource = await readFile(at('og-image.svg'), 'utf8')
const patched = ogSource.replace(
  /(<path id="pandaPath" d=")[^"]*(")/,
  (_, before, after) => before + pandaPath + after,
)
if (patched === ogSource && !ogSource.includes(pandaPath)) {
  throw new Error('og-image.svg has no <path id="pandaPath"> to fill')
}
await writeFile(at('og-image.svg'), patched)
console.log('og-image.svg          glyph synced')

// --- Social card -------------------------------------------------------------
const ogSvg = await readFile(at('og-image.svg'))
await write(
  'og-image.png',
  await sharp(ogSvg, { density: 144 })
    .resize(1200, 630, { fit: 'fill' })
    .png({ compressionLevel: 9, palette: true })
    .toBuffer(),
)

// --- App icons ---------------------------------------------------------------
// The favicon flips colour with the OS theme; rasterised icons need one fixed
// look, so the light-theme plate (ink on paper-white glyph) is baked in.
const iconSvg = await readFile(at('favicon.svg'))
for (const [name, size] of [
  ['apple-touch-icon.png', 180],
  ['icon-192.png', 192],
  ['icon-512.png', 512],
]) {
  await write(
    name,
    await sharp(iconSvg, { density: 384 })
      .resize(size, size, { fit: 'fill' })
      .png({ compressionLevel: 9 })
      .toBuffer(),
  )
}
